version: '3.9'

services:
  db:
    image: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  db-test:
    image: postgres
    ports:
      - ${POSTGRES_PORT_TEST}:5432
    environment:
        - POSTGRES_DB=${POSTGRES_DB_TEST}
        - POSTGRES_USER=${POSTGRES_USER_TEST}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_TEST}
volumes:
  pgdata: