version: '3.9'

services:
  database:
    image: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    volumes:
      - 'pgdata:/var/lib/postgresql/data'

volumes:
  pgdata: