version: '3.9'

services:
  database:
    image: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: tampc1
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: test_db
    volumes:
      - 'pgdata:/var/lib/postgresql/data'

volumes:
  pgdata: